---
- name: Update Aruba Switch Hostname
  gather_facts: no
  hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    pwd_alias: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
    host_alias: "{{ 1000 | random(start=1000) }}"
  
  tasks:
  
    - set_fact:
        generated_password: "{{ pwd_alias }}"
    - set_fact:
        random_number: "{{ host_alias }}"
        
    - name: Write Password to a file
      delegate_to: localhost
      copy:
        content: "{{ generated_password }}"
        dest: ~/$USER/Documents/password_file.txt
    
    - name: Set hostname on the Aruba switch
      aoscx_config:
        commands:
          - "hostname HMLB-{{ random_number }}"
    
    - name: Set admin password for the switch
      aoscx_config:
        commands:
          - "user hladmin group administrators password plaintext {{ generated_password }}"
