---
- name: Update Aruba Switch Hostname
  gather_facts: no
  hosts: all
  collections:
    - arubanetworks.aoscx

  tasks:
  
    - name: Generate random four-digit number
      set_fact:
        random_number: "{{ 1000 | random(start=1000, end=9999) }}"

    - name: Debug random_number
      debug:
        var: random_number

    - name: Set hostname on the Aruba switch
      aoscx_command:
        commands:
          - "hostname HMLB-{{ random_number }}"
